services:
  csharp:
    build: ./csharp/src/VendorConnectorcontainer_name: csharp
    ports: [ "5000:5000" ]
  java:
    build: ./java/vendor-connector
    container_name: java
    ports: [ "8081:8081" ]
  js:
    build: ./js/vendor-connector
    container_name: js
    ports: [ "8082:8082" ]
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: [ "9090:9090" ]
    depends_on: [ csharp, java, js ]
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports: [ "3000:3000" ]
    depends_on: [ prometheus ]
