global:
  scrape_interval: 10s
scrape_configs:
  - job_name: csharp
    static_configs:
      - targets: [ "csharp:5000" ]
    metrics_path: /metrics
  - job_name: java
    static_configs:
      - targets: [ "java:8081" ]
    metrics_path: /actuator/prometheus
  - job_name: js
    static_configs:
      - targets: [ "js:8082" ]
    metrics_path: /metrics
